version: '3.8'

networks:
  net:

volumes:
  db-data:

services:

  nginx:
    image: nginx:latest
    networks:
      - net
    ports:
      - 8181:80
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  php:
    build: ./docker/php/
    networks:
      - net
    ports:
      - "2222:22"
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_DATABASE: monitor
      DB_USERNAME: monitor
      DB_PASSWORD: development
      APP_KEY: base64:499myTpr8iJvYewvoqQfYmobmzUU1DHx7XPx7qF3mnk=

  database:
    image: mysql:5.7
    networks:
      - net
    environment:
      MYSQL_DATABASE: monitor
      MYSQL_USERNAME: monitor
      MYSQL_PASSWORD: development
      MYSQL_ROOT_PASSWORD: common404
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "6033:3306"
